# Generated by Django 5.2.8 on 2025-12-18 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={'permissions': [('can_stop_mailings', 'Возможность приостановить рассылку пользователя'), ('can_view_all_mailings', 'Возможность просматривать все рассылки')], 'verbose_name': 'рассылка', 'verbose_name_plural': 'рассылки'},
        ),
        migrations.AlterModelOptions(
            name='recipient',
            options={'permissions': [('can_view_all_recipients', 'Возможность просматривать всех получателей')], 'verbose_name': 'получатель рассылки', 'verbose_name_plural': 'получатели рассылки'},
        ),
    ]
